name: Documentation
description: Request an update to invalid/outdated documentation
title: "[DOC]"
labels: [🚦 status: awaiting triage]
assignees: nhcarrigan
body:
  - type: markdown
    attributes:
      value: "# Incorrect Documentation"
  - type: textarea
    id: docerrordescription
    attributes:
      label: Describe the error
      description: Please explain the information that is incorrect in the documentation, and why you think it needs to be updated.
    validations:
      required: true
  - type: textarea
    id: expectedinformation
    attributes:
      label: Expected information
      description: What should the documentation actually say here?
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this inaccuracy?
    validations:
      required: false
