name: Other
description: Use this for any other issues. PLEASE do not create blank issues
title: "[OTHER]"
labels: [🚦 status: awaiting triage]
assignees: nhcarrigan
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: input
    id: issuedescription
    attributes:
      label: Describe the issue (a clear and concise description)
    validations:
      required: true
  - type: input
    id: extrainfo
    attributes:
      label: Additional information (extra context of the problem)
    validations:
      required: false
