name: Node.js CI
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Lint Build Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint Source Files
        run: npm run lint
      
      - name: Run Build
        run: npm run build

      - name: Run Unit Tests
        run: npm run coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./coverage.json
          fail_ci_if_error: true
          verbose: true # optional (default = false)